### ISSUE TITLE
When video has embedded captions don't enabled the option to upload one

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#21]
## Expected Behavior

When user mark that video **has NOT captions embedded**, the system enables the upload button
## Current Behavior

When user mark that video **has captions embedded**, the system enables the upload button

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/993369/76169348-0bb95b00-6156-11ea-86c2-35b6952b345f.png)

![image](https://user-images.githubusercontent.com/993369/76169354-1a077700-6156-11ea-8d8b-44478b0398cf.png)

## Possible Solution

If teacher checks that video has embedded video, this accessibility resource is valid.
If teacher checks that video has not embedded video, this accessibility resource isn't valid and system enables the upload button. Them, if teacher uploads an valid caption,  this accessibility resource is valid.
Please, Refer Tasks section of requirement #10

**Comment by CAndresH** [comment]
Camila this requirement is confusing. You mean that the option to upload a caption must always be available?
But if the teacher checks that it does not have an embedded content, should the system enable this option?

In the part of tasks to which you make reference does not say that if the teacher checks the option no captions the system should enable the option to upload content

Tasks
List the tasks required to accomplish the requirement (not exhaustive)
 SYSTEM MUST include SELI's videos contents with captions (embedded or not) for all videos that student may consume.
When TEACHER uploads a video content (not video-only)
 SYSTEM MUST provide a checkbox to TEACHER marks if it is a video-only.
IF TEACHER uploads a video content, i.e. video-only checkbox not checked
 SYSTEM MUST provide a checkbox to TEACHER marks if the video has captions embedded.
IF TEACHER uploads a video content without embedded captions, i.e. embedded captions checkbox not checked
 SYSTEM MUST provide an option to TEACHER uploads captions files
SYSTEM MUST render teacher's video content with it captions, if teacher uploads one

**Comment by CAndresH** [comment]
Or maybe I'm misinterpreting and you mean when a teacher uploaded a caption the next time he edited the content the options for selecting captions should not be available?

**Comment by ecureuill** [comment]
> You mean that the option to upload a caption must always be available?
No
> But if the teacher checks that it does not have an embedded content, should the system enable this option?
Yes

Maybe you are not understanding what's is 
**embedded captions**?

**embedded captions** means that the uploaded video have captions in it stream. 

So, if the video file already has captions (

**Comment by ecureuill** [comment]
It's important to note that this functionality was working correctly before. Maybe, just review the code to undo the modifications in this part.

**Comment by ecureuill** [comment]
![Screenshot_20200313-125357](https://user-images.githubusercontent.com/993369/76637567-c4eaad00-6529-11ea-9f1c-75b28e3e141b.png)

**Comment by ecureuill** [comment]
@CAndresH, for the next bugs/features  the branch name should be the id of the issue. In this case `bug/21`, to be easy to find later.

**Comment by CAndresH** [comment]
please check in ram develop this solution if it is working fine
![image](https://user-images.githubusercontent.com/50594090/79479357-42468900-7fd2-11ea-8a8b-98affbd61e79.png)
![image](https://user-images.githubusercontent.com/50594090/79479386-4d011e00-7fd2-11ea-9c2d-1b3b687aa974.png)
or explain well what is wrong

**Comment by ecureuill** [comment]
Just a sec, I'm writing :stuck_out_tongue_closed_eyes:

**Comment by CAndresH** [comment]
camila errors and warnings are problems that were on the platform since mateo made the code, some are library errors, this type of correction we have thought correct to do at the end when the platform has to be deployed, it could take too long to do this type of corrections now that the final version is not yet

if the functionality is correct and allows you to upload the file this task will be left for the end

**Comment by ecureuill** [comment]
But, as I said, in production this errors are not occurring (see the prints), so they are something new, introduced in develop branch that will be dumped in production, if we neglect it. 

If you guys are okay with that...

But, a solution for a issue/feature is not only achieve the goal no matter what, is part of the solution create it without create new problems.

**Comment by juantenesaca** [comment]
Hello Camilla, I have reviewed the code for inconsistencies but, I did not find anyone because of the warning messages, plus from my side I do not have that warnings in any of that three events. I think it is because I have fixed some dependencies of packages, and now I have completed resolved that.

Please update the project and then run "npm install" in the main folder. Let us now if you still have that issue.

**Comment by ecureuill** [comment]
@caroltaus please test if the errors I pointed in my last commentary (https://github.com/solex2006/SELIProject/issues/21#issuecomment-614730777) was fixed by @juantenesaca  updated.

Each error is set as a task in my comment. If you can't reproduce the errors, mark them as checked (fixed)

**Comment by juantenesaca** [comment]
Hello Caroline, the three warnings Camilla mentions must be reviewed in the console. The error you mention is appart of this line.

**Comment by caroltaus** [comment]
Hi Juan, yes! the errors are still appearing in the console as well:


![errocon1](https://user-images.githubusercontent.com/48024795/80892081-c8372500-8c9e-11ea-8d2d-469e243906c8.jpg)
![errocon2](https://user-images.githubusercontent.com/48024795/80892083-cb321580-8c9e-11ea-9046-c9799816a2b8.jpg)
![errocon3](https://user-images.githubusercontent.com/48024795/80892086-cec59c80-8c9e-11ea-962c-4a7966ba9175.jpg)
![errocon4](https://user-images.githubusercontent.com/48024795/80892087-d1c08d00-8c9e-11ea-996f-ca46acfb771e.jpg)
![errocon5](https://user-images.githubusercontent.com/48024795/80892088-d5541400-8c9e-11ea-9938-8604f9c1ae45.jpg)
![errocon6](https://user-images.githubusercontent.com/48024795/80892089-d84f0480-8c9e-11ea-9723-a230b852bc43.jpg)

**Comment by juantenesaca** [comment]
That is strange. Which OS are you using?

**Comment by caroltaus** [comment]
Linux Ubuntu

**Comment by juantenesaca** [comment]
And the browser? Ok thank you. We can leave this to the final of the project. There are another priorities.

**Comment by caroltaus** [comment]
Chrome! Okay, thank you!
